= CSDL Hệ thống quản lý nhà xe
:experimental:
:source-highlighter:
:toc: none

[plantuml, images/data-table, svg]
....
left to right direction

class User {
	user_id
	full_name
	email
	phone
	password
}



package company.setup {
	class Company {
		company_id
		company_name
		company_desc
		is_lock
	}


    class Employee {
        employee_id
        company_id

        user_id
        is_lock
    }
	
}

package buss.operation {
	class Buss {
		buss_id
		company_id
		buss_type_id
		buss_name
		is_lock
	}
	
	class Buss_Employee {
		employee_id
		buss_id
		is_lock
	}
}


package buss.config {
	class Buss_Type {
		buss_type_id
		name
		description
        total_seats
	}
	
	class Seat_type {
		seat_type_id
		buss_type_id
		name
	}
}

package pos {
	class Buss_point {
		point_id
		location_id
		buss_stop_desc
	}

	class Location #pink {
		location_id
		location_name
		location_parent
	}
}

package trip.setup {
	class Trip_Buss {
		trip_id
		buss_id
		launch_time
		start_point
		end_point
		effective_date_from
		price
		sunday
		monday
		tuesday
		wednesday
		thursday
		friday
		saturday
	}
	
}

package trip.operation {
	class Trip {
		trip_id
		buss_id
		price
		status
		start_time
		start_point
		end_point
	}
	
	class Trip_User {
        trip_user_id
		trip_id
		user_id
		total_price
		status
		confirmed_by
		confirmed_date
	}
	
	class Trip_User_Seat {
		trip_id
		user_id
		seat_type_id
	}
}

Employee::user_id --> User::user_id
Employee::company_id --> Company::company_id

Trip_User_Seat::trip_id --> Trip::trip_id
Trip_User_Seat::user_id --> User::user_id
Trip_User_Seat::seat_type_id --> Seat_type::seat_type_id

Trip_User::user_id --> User::user_id
Trip_User::trip_id --> Trip::trip_id

Seat_type::buss_type_id --> Buss_Type::buss_type_id

Trip::start_point --> Buss_point::point_id
Trip::end_point --> Buss_point::point_id

Buss::company_id --> Company::company_id
Buss::buss_type_id --> Buss_Type::buss_type_id

Buss_Employee::employee_id --> Employee::employee_id
Buss_Employee::buss_id --> Buss::buss_id

Trip_Buss::buss_id --> Buss::buss_id
Buss_point::location_id --> Location::location_id

....