
export enum Authority {
  USER_READ = "USER_READ",
  USER_WRITE = "USER_WRITE",
  ADMIN_READ = "ADMIN_READ",
  ADMIN_WRITE = "ADMIN_WRITE",
  BUSS_STAFF_READ = "BUSS_STAFF_READ",
  BUSS_STAFF_WRITE = "BUSS_STAFF_WRITE",
  CALLER_STAFF_READ = "CALLER_STAFF_READ",
  CALLER_STAFF_WRITE = "CALLER_STAFF_WRITE"
}
