export enum XeRole {
  ROLE_USER = "ROLE_USER",
  ROLE_BUSS_MANAGER = "ROLE_BUSS_MANAGER",
  ROLE_CALLER_STAFF = "ROLE_CALLER_STAFF",
  ROLE_BUSS_STAFF = "ROLE_BUSS_STAFF",
  ROLE_SYSTEM_MANAGER = "ROLE_SYSTEM_MANAGER"
}


