= Đồ án tốt nghiệp Funix
:experimental:
:source-highlighter:
:toc: left
:toclevels: 4

== I. Use Cases

=== Khách Vãng Lai
[NOTE]
====
*Khách Vãng Lai* là người vào web và chưa đăng ký tài khoản. 
====

[plantuml, guest_usecases, svg]     
....
left to right direction
skinparam actorStyle Hollow 
:Khách Vãng Lai: as g
g --> (Tìm chuyến đi)#blue
g --> (Đăng ký tài khoản)#blue
g --> (Lấy lại mật khẩu)#blue
g --> (Đăng nhập)#blue
....


=== Thành Viên
[NOTE]
====
*Thành Viên* là một người dùng điển hình đã đăng ký tài khoản.
====

[IMPORTANT]
====
Tất cả tính năng của người dùng có tài khoản +
đều yêu cầu *đã đăng nhập vào Hệ Thống*
====

[plantuml, User_usecases, svg]     
....
left to right direction
skinparam actorStyle awesome 
:Thành Viên: as u

(Đặt chuyến) as (reserve_trip)
(Hủy chuyến) as (cancel_trip)
(Lịch sử đặt chuyến) as (trip_history)
(Sửa chuyến) as (edit_trip)

 
u --> (Đăng xuất)#blue
u --> (reserve_trip) #blue
u --> (trip_history)#blue
(cancel_trip) .> (reserve_trip) : include
(edit_trip) .> (reserve_trip) : include
....

=== Quản Trị Hệ Thống & Quản Trị Nhà Xe
[NOTE]
====
*Quản Trị Hệ Thống* là chúng ta, tiếp nhận các nhà xe.

để đơn giản hóa chức năng +
khi _xem-tạo-xóa_ 1 nhà xe sẽ +
đồng thời tác động lên *Quản Trị Nhà Xe*
====


[NOTE]
====
*Quản Trị Nhà Xe* là quản lý của một nhà xe nào đó. +
Cùng 1 nhà xe có thể có *nhiều hơn 1 quản lý*. +
 +
Tuy nhiên trong phiên bản của đồ án, +
chỉ cho phép *1 nhà xe có tối đa 1 quản lý* +
để tránh việc xung đột hoặc chồng chéo quyền hạn. +
 +
Khi đi vào hoạt động, tùy theo nhu cầu từng khách hàng, +
có thể khái quát lại và triển khai những tính năng phân quyền chi tiết hơn.
====


[plantuml, sys_admin_usecases, svg]     
....
left to right direction
skinparam actorStyle awesome 

:Quản Trị Hệ Thống: as sa
(Xem-Tạo-Xóa-Khóa-Mở\nNhà Xe) as (buss_operation)
(Xem-Tạo-Xóa\nLoại Xe) as (buss_type)

sa -up-> (buss_operation)#blue
sa -up-> (buss_type)#blue

:Quản Trị Xe: as ba
(Xem-Tạo-Xóa\nHành Trình) as (trip)
(Xem-Tạo-Xóa\nĐiểm Dừng) as (buss_stop)
(Xem-Tạo-Xóa\nĐường Đi) as (path)
(Xem-Tạo-Xóa-Sửa\nHành Trình của Xe) as (buss_trip)
(Xem-Tạo-Xóa-Khóa-Mở\nXe) as (buss)
(Xem-Tạo-Xóa-Khóa-Mở\nNhân Viên Xe) as (buss_staff)
(Xem-Tạo-Xóa-Khóa-Mở\nNhân Viên Tổng Đài) as (caller_staff)

ba -right-> (buss)#blue
(buss) .> (buss_type) : include

ba --> (buss_staff)
ba --> (caller_staff)


ba -up-> (buss_stop)
(buss_trip) .> (trip) : include
(trip) .> (path) : include
(path) .> (buss_stop) : include

....


=== Nhân Viên Xe và Nhân Viên Tổng Đài

[NOTE]
====
*Nhân Viên Xe* là các nhân viên quản lý trực tiếp 1 xe nào đó. +
Vì tình hình thực tế trên xe có thể thay đổi thất thường, +
Nên những người này có quyền hạn cao nhất đối với xe họ quản lý. +
Thể hiện ở quyền *khóa/mở* 1 ghế nào đó trên xe.
====

[NOTE]
====
*Nhân Viên Tổng Đài* có thể xếp vé cho nhiều xe khác nhau +
trong nhà xe mà nhân viên đó phụ trách.
====

[plantuml, Buss_cases, svg]     
....

left to right direction
skinparam actorStyle awesome
:Nhân Viên Tổng Đài: as c
:Nhân Viên Xe: as b

b --> (Khóa/mở\nChỗ)
c --> (hủy-tạo-sửa\nĐặt Chỗ)
c --> (Xác nhận Thanh Toán)
b -left-|> c
 
....


== II. Flow charts

=== 1. Tìm chuyến đi
[plantuml, find_trip, svg]
....
|User| Khách Vãng Lai
	start
	:Mở trang chủ 
	của Hệ Thống;
	fork
		:Chọn 
		<b>Điểm xuất phát</b>;
	fork again
		:Chọn 
		<b>Điểm dừng</b>;
	fork again
		:Chọn 
		<b>Giờ khởi hành</b>;
	end merge
		:Click nút 
		<b>Tìm ngay!</b>;

|System| Hệ Thống

	:Hiển thị kết quả;
	
	#lightgreen:Sẵn sàng cho 
	flow tiếp theo>
....


=== 2. Đặt chỗ 

[plantuml, book_trip, svg]
....

|User| Khách Vãng Lai
	start
	
|System| Hệ Thống

	#lightgreen:Từ kết quả ở 
	<b>Tìm chuyến đi</b> >
	
	if (Tìm thấy chuyến nào không?) then (có)
		|User|
			:Click vào 
			<b>chuyến đi muốn đặt</b>;
	else (không)
	
		|System|
			:Hiển thị 
			<b>Không tìm thấy chuyến nào!</b>;
			
			end
	endif

|System|
	:Chuyển tới màn hình 
	<b>Đặt chỗ</b>;
	
|User|
	fork
		repeat :Click vào\n<b>ghế muốn đặt/hủy</b>;
			repeat while (Hài lòng rồi chứ?) is (Không)
		->Ok;
|System|
	fork again
		:Hiển thị 
		- <b>Tổng tiền</b>
		- <b>Ghế trống</b> 
		- <b>Ghế đang đặt</b>
		- <b>Ghế bị khóa</b>
		thời gian thực;
		
	end fork
	
	if (lựa chọn hợp lệ?) then (có)
		
		:Mở nút 
		<b>Đặt ngay!</b>;
		
	else (không)
		
		:Khóa và Làm mờ nút 
		<b>Đặt ngay!</b>;
		end
	endif

|User|
	:click nút 
	<b>Đặt ngay!</b>;
	
|System|

	if (Đã đăng nhập?) then (Đúng)
		
	else (sai)
		
		#lightgreen:Chuyển tới màn hình 
		<b>Đăng nhập</b> >
		
		if (Đăng nhập\n<b>thành công</b>?) then (Sai)
			end
		else (Đúng)
		
		endif
			
	endif

	:Lưu thông tin
	<b>vào CSDL</b>;
	
	fork
		:Gửi tin thành công 
		<b>qua Email</b>;
	fork again
		:Hiển thị thông báo 
		<b>Đặt chỗ thành công!</b>;
	end fork
	
	stop
....

=== 3. Đăng nhập
[plantuml, log_in, svg]
....
|Guest| Khách Vãng Lai
	start
	
	:Mở màn hình 
	<b>Đăng nhập</b>;
	
	repeat :Nhập thông tin đăng nhập;
	
		:Enter hoặc click nút 
		<b>Đăng nhập</b>;
	
|System| Hệ Thống
		repeat while (Thông tin hợp lệ?) is (Không)
	->Đúng;
	
	:Lưu thông tin liên quan
	vào session hiện tại;
	
	if (Đăng nhập từ\nflow dở dang?) then (có)
		:Tiếp tục flow đó;
		
	else (không)
		:Chuyển tới màn hình 
		<b>Quản trị tài khoản</b>;
		
	endif
	
	stop
....

=== 4. Đăng ký tài khoản

.Tài khoản trôi
[IMPORTANT]
====
Khi khách đặt xe trực tiếp với tổng đài hoặc lái xe, +
Khách chỉ cung cấp số điện thoại, +
Nhà xe cũng không cần hỏi tên, +
đây là hoạt động thực tế đang diễn ra. +
Chúng ta *không nên phá vỡ luồng đi này*. +

Trong dự án này, +
khi nhà xe đặt chỗ cho khách theo số điện thoại +
Hệ Thống sẽ tìm tài khoản theo số điện thoại đó, +
Hoặc tạo 1 tài khoản trôi chỉ gồm duy nhất số điện thoại. +

Khi khách hàng nào đó tạo mới tài khoản, +
Nếu nhập vào số điện thoại thuộc *tài khoản trôi*, +
Thì các thông tin đăng ký sẽ được gán cho tài khoản này. +

Như vậy chỉ bằng số điện thoại, +
Khách sẽ thấy luôn được lịch sử đi xe của mình, +
Dù mới lần đầu đăng ký.

====

[plantuml, register, svg]
....
|User| Khách Vãng Lai
	start
	
	:Mở màn hình 
	<b>Đăng ký</b>;
	
	repeat :Nhập\n<b>Họ và Tên</b>,\n<b>Số điện thoại</b>,\n<b>Email</b>,\n<b>Mật khẩu</b>,\n<b>Nhập lại mật khẩu</b>;
	
		:Click nút <b>Đăng ký</b>;
	
|System| Hệ Thống
		repeat while (Thông tin hợp lệ?) is (Không)
	->Có;
		
	if (Số điện thoại của\n<b>tài khoản trôi</b>?) is (Đúng) then
		
		:Gán thông tin đăng ký 
		vào tài khoản đó;
		
	else (Sai)
	
		:Tạo mới bản ghi 
		vào CSDL;
		
	endif
	
	:Chuyển tới màn hình 
	<b>Đăng nhập</b>;
	
	stop
....

=== 5. Lấy lại mật khẩu

[plantuml, find_password, svg]
....
|User| Khách Vãng Lai
	start
	
	:Mở màn hình 
	<b>Lấy lại mật khẩu</b>;
	
	:Nhập 
	<b>Email</b>;
	
	:Click nút 
	<b>Xác nhận</b>;
	
|System| Hệ Thống

	if (Email tồn tại?) is (Không) then
		
		:Hiển thị 
		<b>Email không tồn tại!</b>;
		
		end
	else (có)
		fork
			:Gửi link đổi mật khẩu
			tới email đã nhập;
		fork again
			:Hiển thị 
			<b>Mở email để tiếp tục đổi mật khẩu!</b>;
			
		end merge
		
		|User|
			:Click link 
			<b>Đổi mật khẩu</b> 
			nhận được trong email;
	endif

|System|
	
	#lightgreen:Hiện màn hình
	<b>Đổi mật khẩu</b> >
|User|
	
	repeat :Nhập mật khẩu \n<b>2 lần</b>;
		:Click nút <b>Đổi mật khẩu</b>;

|System| Hệ Thống
		repeat while (Mật khẩu khớp?) is (Không)
	->Có;
	
	:Hiển thị
	<b>Đổi mật khẩu thành công!</b>
	và nút 
	<b>Click để đăng nhập</b> ;
	
	stop
....


=== 6. Tài khoản của tôi

==== 6.A. Đăng xuất

[plantuml, log_out, svg]
....
|User| Thành Viên
	start
	
	:Click nút 
	<b>Đăng xuất</b>;
	
|System| Hệ Thống

	:Xóa toàn bộ 
	<b>phiên đăng nhập</b>;
	
	:Chuyển tới màn hình 
	<b>Đăng nhập</b>;
	
	stop
....

==== 6.B. Đổi mật khẩu

[plantuml, change_password, svg]
....
|User| Thành Viên

	start
	
	:Mở màn hình 
	<b>Đổi mật khẩu</b>;
	
	repeat :Nhập\n- <b>Mật khẩu cũ</b>,\n- 2 lần <b>Mật khẩu mới</b>;
	
		:Click nút
		<b>Đồng ý</b>;
	
|System| Hệ Thống
		repeat while (Hợp lệ?) is (Không)
	->Có;
	
	:Hiển thị 
	<b>Đổi mật khẩu thành công!</b>;
	
	stop
....

==== 6.C. Xem thông tin tài khoản

[plantuml, view_my_info, svg]
....
|User| Thành Viên

	start
	
	:Mở màn hình 
	<b>Thông tin tài khoản</b>;
	
|System| Hệ Thống

	:Hiển thị 
	- <b>Họ tên</b>
	- <b>Số điện thoại</b>
	- <b>Địa chỉ Email</b>;
	
	#lightgreen:Sẵn sàng cho
	<b>flow tiếp theo</b> >
....

==== 6.D. Sửa thông tin tài khoản

[plantuml, change_my_acc_info, svg]
....
|User| Thành Viên
	
	#lightgreen:Từ màn hình 
	<b>Thông tin tài khoản</b>;
	
	:Click nút
	<b>Sửa</b>;
	
|System| Hệ Thống

	:Hiển thị các input
	- <b>Họ tên</b>
	- <b>Số điện thoại</b>
	- <b>Địa chỉ Email</b>;

|User| 
	repeat:Sửa thông tin theo ý muốn;
	
		:Click nút
		<b>Đồng ý</b>;

|System|
		repeat while (Thông tin hợp lệ?) is (Sai)
	->Đúng;
	
	:Hiện tin nhắn
	<b>Cập nhật thành công!</b>;
	
	stop
	
....

=== 7. Chuyến đi của tôi

==== 7.A. Lịch sử đặt chuyến

[plantuml, View_Trip_History, svg]
....

|User| Thành Viên

	start
	
	:Mở màn hình 
	<b>Lịch sử đặt chuyến</b>;
	
|System| Hệ Thống

	:Hiển thị 
	<b>Lịch sử đặt chuyến</b> 
	của Thành Viên này,
	chia theo tab: 
	<b>- Chờ khởi hành</b> <i>(Mặc định)</i>
	<b>- Đã hủy </b>
	<b>- Đã khởi hành</b>;

	#lightgreen:Sẵn sàng cho 
	flow tiếp theo>

end

....

==== 7.B. Hủy chuyến

[plantuml, cancel_trip, svg]
....

|User| Thành Viên
	start
|System| Hệ Thống
	
	#lightgreen:Từ màn hình 
	<b>Lịch sử đặt chuyến</b> >
	
|User| Thành Viên

	:Chọn các chuyến 
	muốn hủy bỏ;
	
	:Click nút 
	<b>Hủy</b>;
	
|System|
	:Bật pop-up xác nhận;
|User|

	if (Click hoặc chọn) is (Khác) then
		|System|
		:Tắt pop-up;
		end
	else (nút <b>Đồng ý</b>)
		|System|
			:Hủy các 
			<b>chuyến được chọn</b>;
			
		 	:Hiển thị tin nhắn
		 	<b>Hủy chuyến thành công</b>;
	endif
	
	stop
....


==== 7.C. Sửa chuyến đã đặt

[plantuml, update_trip, svg]
....

|User| Thành Viên
	start
|System| Hệ Thống
	
	#lightgreen:Từ màn hình 
	<b>Lịch sử đặt chuyến</b> >
	
|User|
	:Click vào 
	<b>số hiệu chuyến</b> muốn sửa;

|System|
	:Chuyến tới màn hình 
	<b>Sửa chuyến</b>;
	
	fork
|User|
	repeat :Click vào chỗ ngồi\nmuốn <b>Đặt/Hủy</b>;
		repeat while (Đồng ý với lựa chọn này?) is (Không)
	->Có;
|System|
	fork again
		:Hiển thị 
		<b> - Tổng tiền</b>,
		<b> - Ghế trống</b> 
		<b> - Ghế đang đặt</b>
		thời gian thực;
|System|

	end fork
	
	if (Lựa chọn hợp lệ?) then (Có)
		:Mở nút 
		<b>Cập nhật</b>;
		
	else (không)
		:Tắt và làm mờ nút 
		<b>Cập nhật</b>;
		
		end
	endif
|User|
	:Click nút 
	<b>Cập nhật</b>;
	
|System|
	:Lưu thông tin vào CSDL;
	
	:Gửi Email xác thực 
	đến khách hàng;
	
	:Hiện tin nhắn
	<b>Sửa chuyến thành công!</b>;
	stop
....


=== 8. Quản lý Nhà Xe

==== 8.A. Danh sách Nhà Xe

[plantuml, list_buss_org, svg]
....
|Sys Admin| Quản Trị Hệ thống
	start
	:Mở màn hình 
	<b>Quản lý Nhà Xe</b>;

|System| Hệ Thống
	:Hiển thị tất cả 
	<b>Nhà Xe</b> theo tab:
	- <b>Đang hoạt động</b> <i>(Mặc định)</i> 
	- <b>Đang khóa</b>;
	
	#lightgreen:Sẵn sàng cho 
	flow tiếp theo>
....


==== 8.B. Thêm Nhà Xe

[plantuml, add_buss_org, svg]
....
|Sys Admin| Quản Trị Hệ Thống

	#lightgreen:Từ màn hình 
	<b>Danh sách Nhà Xe</b> >
	
	:Click nút 
	<b>Thêm Nhà Xe</b>;

|System| Hệ Thống
	:Chuyển tới màn hình
	<b>Tạo nhà Xe</b>;

|Sys Admin|
	repeat :Nhập\n- <b>Tên nhà xe <color:red>*</color></b>\n- <b>Quản trị nhà xe <color:red>*</color></b>\n- <b>Mô tả</b>\n- <b>Ảnh đại diện</b>;
	
		:Click nút 
		<b>Đồng ý</b>;

|System|
		repeat while (<b>Tên Nhà Xe</b> hợp lệ + khả dụng,\n<b>Người được chọn</b> chưa là Quản Lý Nhà Xe) is (<b>Sai</b>\nHiện thông báo lỗi)
	->Đúng;
	:Thêm <b>Nhà Xe</b> 
	vào CSDL;
	
	:Chuyển tới màn hình 
	<b>Danh sách Nhà Xe</b>;
	
	stop
....



==== 8.C. Xóa Nhà Xe

IMPORTANT: Nhà xe chỉ được xóa khi chưa có chuyến đi nào được thực hiện trong hệ thống.

[plantuml, delete_buss_org, svg]

....
|Sys Admin| Quản Trị Hệ Thống
	
	#lightgreen:Từ màn hình 
	<b>Danh sách Nhà Xe</b> >
	
	:Chọn các nhà xe muốn xóa
	ở cột <b>checkbox</b> 
	phía cuối cùng;
	
	:Click nút 
	<b>Xóa</b>;
	
|System| Hệ Thống
	if (Các nhà xe đều \n<b>chưa chạy chuyến nào</b>?) then (Đúng)
		:Xóa tất cả 
		nhà xe được chọn 
		và thông tin liên quan;
		
		:Hiển thị tin 
		<b>Xóa thành công!</b>;
		
	else (Sai)
		:Hiển thị thông báo lỗi,
		liệt kê 
		- <b>tên nhà xe</b>
		- <b>các chuyến đã chạy</b>;
		
	endif
	
	stop
....

==== 8.D. Khóa Nhà Xe

[plantuml, lock_buss_orgs, svg]

....
|Sys Admin| Quản Trị Hệ Thống
	
	#lightgreen:Từ màn hình 
	<b>Danh sách Nhà Xe</b> >
	
	:Chọn <b>Các nhà xe muốn khóa</b>
	ở cột <b>checkbox</b> 
	phía cuối cùng;
	
	:click nút 
	<b>Khóa</b>;
	
|System| Hệ Thống
	:Khóa tất cả 
	<b>Nhà Xe</b> được chọn;
	
	:Cập nhật lại 
	danh sách hiển thị;
	
	:Hiển thị tin nhắn 
	<b>Đã khóa thành công</b>;
	
	stop
....

==== 8.E. Mở khóa Nhà Xe

[plantuml, unlock_buss_org, svg]

.... 
|Sys Admin| Quản Trị Hệ Thống

	#lightgreen:Từ màn hình 
	<b>Danh sách Nhà Xe</b> >
	
	:click vào tab 
	<b>Đang khóa</b>;
	
|System| Hệ Thống
	if (Có nhà xe nào đang khóa không?) is (Có) then
		|Sys Admin|
			:Chọn <b>Các nhà xe muốn mở khóa</b>
			ở cột <b>Checkbox</b> 
			phía cuối cùng;
		
	else (Không) 
		|System|
		end	
	endif

|Sys Admin|
	:click nút 
	<b>Mở khóa</b>;

|System|
	
	:Mở khóa tất cả 
	<b>Nhà xe được chọn</b>;
	
	:Cập nhật lại 
	danh sách hiển thị;
	
	:Hiển thị tin nhắn 
	<b>Mở khóa thành công</b>;

	stop
....

=== 9. Quản lý Loại Xe


==== 9.A. Danh sách Loại Xe


[plantuml, list_buss_types, svg]
....
|Sys Admin| Quản Trị Hệ Thống
	start
	:Mở màn hình 
	<b>Danh sách Loại Xe</b>;

|System| Hệ thống
	:Hiển thị tất cả
	<b>Loại Xe</b>;
	
	#lightgreen:Sẵn sàng cho 
	flow tiếp theo>
....




==== 9.B. Thêm Loại Xe


[plantuml, add_buss_type, svg]
....
|Sys Admin| Quản Trị Hệ Thống
	#lightgreen:Từ màn hình 
	<b>Danh sách Loại Xe</b> >
	
	:Click nút 
	<b>Thêm loại xe</b>;

|System| Hệ thống
	:Chuyển tới màn hình
	<b>Thêm Loại Xe</b>;

|Sys Admin|
	:Nhập
	<b>- Tên Loại Xe</b> 
	<b>- Mô tả</b>
	<b>- Số lượng ghế</b> 
	<b>- File sơ đồ xe</b>
	<b>- Ảnh đại diện</b>;

	:Click nút 
	<b>Tiếp theo</b>;

|System|
	:Chuyển tới màn hình 
	<b>Thiết lập ghế</b>;
	
	:Tạo input 
	- Nhập tên
	- Nhập mô tả
	cho	<b>số lượng ghế</b>
	đã nhập bước trước;

|Sys Admin|
	
	:Nhập 
	<b>- Tên Ghế</b>
	<b>- Mô tả</b> <i>(Không bắt buộc)</i>
	cho mỗi ghế;
	
	:Click nút 
	<b>Đồng ý</b>;


|System|

	if (Thông tin hợp lệ?) then (Đúng)
	
		:Lưu loại xe mới 
		vào CSDL;
		
	else (Sai)
		:Hiển thị thông báo lỗi
		tương ứng;
		end
	endif
	
	:Chuyển tới màn hình
	<b>Danh sách Loại Xe</b>;
	
	stop
....



==== 9.C. Xóa Loại Xe


[plantuml, delete_buss_type, svg]

....
|Sys Admin| Quản Trị Hệ Thống
	#lightgreen:Từ màn hình 
	<b>Danh sách Loại Xe</b> >
	
	:Chọn Loại Xe muốn xóa
	ở cột <b>Checkbox</b> 
	phía cuối cùng;
	
	:Click nút <b>Xóa</b>;
	
|System| Hệ Thống

	if (Hệ thống không có xe nào\nthuộc những loại này?) then (Đúng)
		:Xóa tất cả 
		<b>Loại Xe</b> được chọn;
		
		:Hiện tin nhắn
		<b>Xóa thành công!</b>;
		
	else (Sai)
		:Hiển thị danh sách
		xe thuộc loại này
		và báo lỗi;
		
	endif
	
	stop
....




=== 10. Quản lý Xe

==== 10.A. Danh sách Xe


[plantuml, list_of_busses, svg]
....
|Buss Admin| Quản Trị Nhà Xe
	start
	:Mở màn hình 
	<b>Danh sách Xe</b>;

|System| Hệ Thống
	:Hiển thị tất cả xe
	của nhà xe này;
	
	#lightgreen:Sẵn sàng cho
	flow tiếp theo>
....


==== 10.B. Thêm Xe

[plantuml, add_buss, svg]
....
|Buss Admin| Quản Trị Nhà Xe

	#lightgreen:Từ màn hình
	<b>Danh sách Xe</b> >
	
	:click nút 
	<b>Thêm Xe</b>;

|System| Hệ thống

	:Chuyển tới màn hình\n<b>Thêm Xe</b>;
|Buss Admin|
	repeat :Nhập\n- <b>Tên Xe <color:red>*</color></b>\n- <b>Mô tả</b>\n- <b>Ảnh đại diện</b>\n- <b>Kiểu Xe <color:red>*</color></b>;
			
		
		
		:Click nút
		<b>Đồng Ý</b>;

|System|
		repeat while (Thông tin hợp lệ?) is (<b>Không</b>\nHiện thông báo lỗi)
	->Có;
	:Thêm xe vào CSDL;
		
	:Chuyển tới màn hình
	<b>Danh sách Xe</b>;
	
	stop
....


==== 10.C. Xóa Xe


[plantuml, delete_buss, svg]

....
|Buss Admin| Quản Trị Nhà Xe
	#lightgreen: Từ màn hình
	<b>Danh sách Xe</b> >

	:Chọn các Xe muốn xóa
	ở cột <b>checkbox</b> 
	phía cuối cùng;
	
	:click nút
	<b>Xóa</b>;
|System| Hệ thống
	if (Chưa Xe nào\nđược đặt chuyến?) then (Đúng)
		
		:Xóa các xe
		được chọn;
		
		:Hiện tin nhắn
		<b>Đã xóa thành công!</b>;
		
	else (Sai)
		:Hiện tin nhắn lỗi
		và danh sách chuyến tìm được!;
	endif
	
	stop
....


==== 10.D. Khóa Xe

[TIP] 
====
Khóa xe sẽ gỡ xe này  +
khỏi kết quả tìm kiếm hành trình!
====

[plantuml, lock_buss, svg]
....
|Buss Admin| Quản Trị Nhà Xe

	#lightgreen:Từ màn hình
	<b>Danh sách Xe</b> >
	
	fork
		:Chọn các Xe muốn xóa
		ở cột <b>checkbox</b> 
		phía cuối cùng;
	fork again
		:Nhập ngày 
		<b>Bắt đầu khóa</b>;
	fork again
		:Nhập ngày
		<b>Kết thúc khóa</b>
		(Để trống = vô thời hạn);
	end merge
	
	:Click nút
	<b>Khóa</b>;
|System| Hệ thống

if (Có bất cứ khách nào đang đặt?) then (Đúng!)
	
	:Hiện yes/no pop-up
	<b>Có Xe đang được đặt</b>,
	<b>Bạn vẫn muốn khóa chứ?</b>;
	
	:lock all selected busses;
	
	:move those busses to <b>Locking</b> tab;
	:display lock successfully message;
else (Đúng)
	:display error message;
endif
	stop
....

==== 10.E. Mở khóa Xe

[plantuml, unlock_busses, svg]

.... 
|Buss Admin|
#lightgreen:from <b>List of Busses</b> flow>
:click on <b>Locking</b> tab;
|System|
if (has any locking buss?) is (no) then
	end
else (yes) 
	:select <b>busses</b> want to unlock
		on <b><color:red>check boxes</color></b> column;	
endif

|Buss Admin|
:click <b><color:red>Unlock</color></b> button;

|System|
if (is valid) then (yes)
	:unlock all selected busses;
	:move those busses out of <b>Locking</b> tab;
	:display lock successfully message;
else (no)
	:display error message;
endif
stop
....

=== 11. Quản lý Nhân Viên Tổng Đài


==== 11.A. Danh sách Nhân Viên Tổng Đài

[plantuml, list_of_caller_staffs, svg]
....
|Buss Admin|
start
:go to <b>Manage Callers</b> view;

|System|
:show all <b>Caller Staffs</b> in System;
#lightgreen:ready to next flow>
....

==== 11.B. Thêm Nhân Viên Tổng Đài

==== 11.C. Xóa Nhân Viên Tổng Đài

==== 11.D. Khóa Nhân Viên Tổng Đài

==== 11.E. Mở khóa Nhân Viên Tổng Đài

=== 12. Quản lý Nhân Viên Xe

==== 12.A. Danh sách Nhân Viên Xe

==== 12.B. Thêm Nhân Viên Xe

==== 12.C. Xóa Nhân Viên Xe

==== 12.D. Khóa Nhân Viên Xe

==== 12.E. Mở Khóa Nhân Viên Xe

=== 13. Quản lý Điểm Dừng

==== 13.A. Danh sách Điểm Dừng

==== 13.B. Thêm Điểm Dừng

==== 13.C. Xóa Điểm Dừng

=== 14. Quản lý Đường Đi

==== 14.A. Danh sách Đường Đi

==== 14.B. Thêm Đường Đi

==== 14.C. Xóa Đường Đi

==== 14.D. Tạo Đường Đi mới từ Đường Đi đang chọn.

=== 15. Quản lý Hành Trình

==== 15.A. Danh sách Hành Trình

==== 15.B. Thêm Hành Trình

==== 15.C. Xóa Hành Trình

=== 16. Quản lý Chuyến Xe

==== 16.A. Danh sách Chuyến Xe

==== 16.B. Thêm Chuyến Xe

==== 16.C. Sửa Chuyến Xe

==== 16.D. Xóa Chuyến Xe

=== 17. Quản lý Xe Chạy

==== 17.A. Danh sách Chuyến Xe đặt trước

==== 17.B. Thêm Ghế đặt trước

==== 17.C. Sửa Ghế đặt trước

==== 17.D. Khóa Ghế

==== 17.E. Mở khóa Ghế

==== 17.F. Xác nhận Thanh Toán

