xekhach:
  security:
    allowedHeaders: ["Origin", "Access-Control-Allow-Origin", "Content-Type",
                     "Accept", "Jwt-Token", "Authorization", "Origin, Accept", "X-Requested-With",
                     "Access-Control-Request-Method", "Access-Control-Request-Headers"]
    exposedHeaders: ["Origin", "Content-Type", "Accept", "Jwt-Token", "Authorization",
                     "Access-Control-Allow-Origin", "Access-Control-Allow-Origin", "Access-Control-Allow-Credentials"]
    allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    jwtSecret: "D!1qYZk3S1d9@cbFnE$E*$pGB$QS3rC"
    tokenPrefix: "Bearer "
    tokenHeader: "Jwt-Token"
    expirationTime: 432000000 # 5 days in milliseconds
    authorities: "authorities"
    httpMethodOption: "OPTIONS"
    publicUrls: ["/images/**", "/resource/**", "/common-update/**"]
    maximumNumberOfLoginAttempts: 5
    jwtIssuer: "TimXeKhach"
    jwtAudience: "TimXeKhachAdministration"
    allowedOrigins: ["http://localhost:4200"]
    resourcePath: "${APPDATA}/xekhach/"
    resourceUrl: "${xekhach.security.apiUrl}resource/"
    apiUrl: "http://localhost:8081/api/"



server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://timxekhach.tech:3306/timxekhach?useUnicode=yes&characterEncoding=UTF-8
    password: p@iGoec414100
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: "/resource/**"
  web:
    resources:
      static-locations:  file:/${xekhach.security.resourcePath}/

  freemarker:
    enabled: true
    check-template-location: false